### ISSUE TITLE
Question: Project Status?

### ISSUE THREAD

**Issue by zhengpd** [preservim/vim-markdown#567]
Is this project being maintained? There are many open issues and PRs.

**Comment by alerque** [comment]
c.f. #484

A lot of people use this and questions in issues sometimes get answered by other users, but I haven't seen "signs of life" from maintainer(s) in a couple years.

**Comment by zhengpd** [comment]
@alerque Yes I can also see the users are active. Maybe it's time for someone to maintain a fork to review the issues and PRs .

**Comment by alerque** [comment]
I believe @shirosaki has some access to this repository and was the most active maintainer for some time since @plasticboy has been involved, but he seems to be away from it a bit too. At some point @hallison had a noteworthy fork but I'm not sure what the status of that is.

I would be willing to help facilitate a community fork under the auspices of [preservim](https://github.com/preservim). As you can see from the lineup there taking popular VIM plugins that the original authors have moved on from but were willing to turn over to community management is something I've helped with a few times with some success.

If that's going to happen my preference is to to give lots of time for original contributors to weigh in and hopefully actually pass of the repository once we settle trust issues and discuss new maintainer options. It's worth the process dragging out a little to get the automatic migration of all current users without them realizing there has been a fork.

**Comment by plasticboy** [comment]
Hi @alerque,
I would be happy to hand this repository over to preservim. As is probably obvious, I haven't had time to work on it in quite some time. Let me know how I can help.

**Comment by alerque** [comment]
Hey @plasticboy! Thanks for dropping by so soon. I'd be glad to help the process through. 

1. For starters I sent you an invite just now to the Preservim org on GitHub. Once you accept that you should be able to use the "danger zone" at the bottom of [the settings page](https://github.com/plasticboy/vim-markdown/settings) to "transfer ownership" to the organization. 

    - You will still be marked as the owner of the repository and have full permissions on it there (unless you ever decide to recuse yourself).
	- GitHub will take care of adding redirects from the current URL to the new one. These will work automatically form both http links and git access, so *nobody currently using or linking to the repository here will even notice*. The only caveat to this is that if you then fork the repository yourself back to your personal account all the redirects will be useless because everybody will start seeing your fork again. For this reason once you migrate the repository to the org I suggest you don't fork it yourself and just operate directly on it there if you were to ever do development work on it again.

2. I started a [markdown-contributors](https://github.com/orgs/preservim/teams/markdown-contributors) team. We can add people have earned some trust through past contributions by inviting them to join that team. You can be as hands on off as you like and I'll fill in the gaps here. My idea would be to review who has been good contributors in the past and see if anybody wants to jump in, while also putting the word out that anybody wishing to jump in will be considered. I usually want to see people help with existing issues and submit some PRs before giving them powers, but having the team makes it easy to manage without making the project too vulnerable. Usually what I do is setup permissions so that any team members can merge PRs provided they have one approving review. This enables any of the team to review and handle user contributions, but they can't just stuff their own stuff through unilaterally, they need at least one signoff from somebody else.

3. I will put it on my list to sort though existing PRs and do some issue triage.

4. We should setup some more CI to lint and confirm that changes work as expected on VIM & NeoVIM. Eventually this can be expanded to a regression suite to make sure old bits don't break with new changes.

5. Anybody with feedback on existing forks and know where useful things that haven't been contributed here because of apparent inactivity are encouraged to chime in!

**Comment by alerque** [comment]
I'm closing this issue since the repository has migrated, but **I'm leaving it pinned because we still need contributors!** There are tons of issues to triage, PRs to review, and things to fix and do. Know that anybody is free to jump in. I'll be watching activity on this project –even less glamorous things like commenting on existing issues– looking for anybody that is making positive contributions and be inviting those folks to use elevated privileges to more done with less friction. Jump in!
